<?php 
$detail = array(
	"name"        => "Hoa hậu Kỳ Duyên - Tròn một năm đăng quang với tinh thần 'thép đã tôi thế đấy'",
	"description" => "Hoa hậu Việt Nam 2014 Nguyễn Cao Kỳ Duyên đã trải qua một năm đầy thăng trầm và nếm trải đủ mọi cung bậc cảm xúc kể từ khi nhận chiếc vương miệng danh giá.",
	"attrs"       => array(
		"color"   => "red",
		"text-decoration" => "underline"
	)
);
echo $this->partial("frame.phtml",$detail);