<?php 
$detail =array(
	 array(
		"name"        => "Hoa hậu Kỳ Duyên - Tròn một năm đăng quang với tinh thần 'thép đã tôi thế đấy'",
		"description" => "Hoa hậu Việt Nam 2014 Nguyễn Cao Kỳ Duyên đã trải qua một năm đầy thăng trầm và nếm trải đủ mọi cung bậc cảm xúc kể từ khi nhận chiếc vương miệng danh giá.",
		"attrs"       => array(
			"color"   => "red",
			"text-decoration" => "underline"
		)
	),
	 array(
		"name"        => "Grammy 2016: Taylor Swift không phải đấu với Adele",
		"description" => "Ngất ngây nhan sắc tựa 'nữ thần' của Miranda Kerr tại sự kiện Ngất ngây nhan sắc tựa 'nữ thần' của Miranda Kerr tại sự kiện",
		"attrs"       => array(
			"color"   => "red"
		)
	)
);
echo $this->partialLoop("frame.phtml",$detail);