<?php 
	$formLogin->prepare();
	$elementEmail    = $formLogin->get("my-email");
	$elementPassword = $formLogin->get("my-password");
	$btnSubmit       = $this->formElement($formLogin->get("my-button-submit"));


	$frame_form = array(
		array(
			"label" => $this->formLabel($elementEmail),
			"input" => $this->formElement($elementEmail),
			"class" => "col-sm-9",
			"error" => $this->formElementError($elementEmail)
		),
		array(
			"label" => $this->formLabel($elementPassword),
			"input" => $this->formElement($elementPassword),
			"class" => "col-sm-9",
			"error" => $this->formElementError($elementPassword)
		),
		array(
			"label" => null,
			"input" => $btnSubmit,
			"class" => "col-sm-offset-3 col-sm-9",
		),
	);	
?>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-lock"></span>Login
			</div>
			<div class="panel-body">
				<?php 
					echo $this->form()->openTag($formLogin);
						echo $this->partialLoop("form-group.phtml",$frame_form);
					echo $this->form()->closeTag();
				?>			
			</div>
			<div class="panel-footer">
				Not Registred? <a href="http://www.jquery2dotnet.com">Register here</a>
			</div>
		</div>
	</div>
</div>